import { Document, Page, Text, View, Image } from '@react-pdf/renderer'
import { styles, colors } from './styles'

function fmt(pence: number) {
  return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(pence / 100)
}

function fmtDate(d: string) {
  return new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(d))
}

export function InvoicePDF({ job }: { job: any }) {
  const contractor = job.contractor
  const variations = job.variations ?? []
  const signedVariations = variations.filter((v: any) => v.status === 'signed')
  const variationsTotal = signedVariations.reduce((s: number, v: any) => s + v.cost, 0)
  const grandTotal = job.original_value + variationsTotal

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>{contractor?.company_name || contractor?.full_name || 'Contractor'}</Text>
            <Text style={styles.docTitle}>Final Invoice with Variations</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={{ fontSize: 9, color: colors.gray400 }}>Invoice date</Text>
            <Text style={{ fontSize: 10 }}>{fmtDate(new Date().toISOString())}</Text>
          </View>
        </View>

        {/* Job & Client */}
        <View style={[styles.row, { marginBottom: 24 }]}>
          <View style={{ flex: 1 }}>
            <Text style={styles.sectionTitle}>Job</Text>
            <Text style={styles.value}>{job.job_name}</Text>
            <Text style={[styles.value, { color: colors.gray600, marginTop: 2 }]}>{job.address}</Text>
          </View>
          <View style={{ flex: 1, alignItems: 'flex-end' }}>
            <Text style={styles.sectionTitle}>Bill To</Text>
            <Text style={styles.value}>{job.client_name}</Text>
            <Text style={[styles.value, { color: colors.gray600, marginTop: 2 }]}>{job.client_email}</Text>
            {job.client_phone && (
              <Text style={[styles.value, { color: colors.gray600 }]}>{job.client_phone}</Text>
            )}
          </View>
        </View>

        {/* Line items */}
        <View style={styles.tableHeader}>
          <Text style={[styles.colDescription, { fontSize: 8, fontFamily: 'Helvetica-Bold', color: colors.gray600 }]}>Description</Text>
          <Text style={[styles.colDate, { fontSize: 8, fontFamily: 'Helvetica-Bold', color: colors.gray600 }]}>Date</Text>
          <Text style={[styles.colAmount, { fontSize: 8, fontFamily: 'Helvetica-Bold', color: colors.gray600 }]}>Amount</Text>
        </View>

        {/* Original contract */}
        <View style={styles.tableRow}>
          <Text style={[styles.colDescription, { fontSize: 10 }]}>Original contract value</Text>
          <Text style={[styles.colDate, { fontSize: 10, color: colors.gray600 }]}>{fmtDate(job.created_at)}</Text>
          <Text style={[styles.colAmount, { fontSize: 10, fontFamily: 'Helvetica-Bold' }]}>{fmt(job.original_value)}</Text>
        </View>

        {/* Signed variations */}
        {signedVariations.map((v: any) => {
          const isNegative = v.cost < 0
          const displayCost = isNegative ? fmt(v.cost) : `+${fmt(v.cost)}`
          const costColor = isNegative ? colors.red : colors.green
          return (
            <View key={v.id} style={styles.tableRow}>
              <View style={styles.colDescription}>
                <Text style={{ fontSize: 10 }}>{v.description}</Text>
                <Text style={{ fontSize: 8, color: costColor, marginTop: 2 }}>✓ Signed by client</Text>
              </View>
              <Text style={[styles.colDate, { fontSize: 10, color: colors.gray600 }]}>{fmtDate(v.date)}</Text>
              <Text style={[styles.colAmount, { fontSize: 10, fontFamily: 'Helvetica-Bold', color: costColor }]}>{displayCost}</Text>
            </View>
          )
        })}

        {/* Total */}
        <View style={[styles.row, { marginTop: 16 }]}>
          <View style={{ flex: 1 }} />
          <View style={styles.totalBox}>
            <Text style={styles.totalLabel}>Total Due</Text>
            <Text style={styles.totalAmount}>{fmt(grandTotal)}</Text>
            {variationsTotal !== 0 && (
              <Text style={{ fontSize: 8, color: '#BFDBFE', marginTop: 4 }}>
                {variationsTotal > 0 ? '+' : ''}{fmt(variationsTotal)} from signed variations
              </Text>
            )}
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by VarTrack · All variations signed by client</Text>
          <Text style={styles.footerText}>Electronic signatures valid under Electronic Communications Act 2000</Text>
        </View>
      </Page>
    </Document>
  )
}
