import { Page, Text, View, Image, Document } from '@react-pdf/renderer'
import { styles, colors } from './styles'

function fmt(pence: number) {
  return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(pence / 100)
}

function fmtDate(d: string) {
  return new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(d))
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function VariationPDF({ variation }: { variation: any }) {
  const contractor = variation.job?.contractor
  const job = variation.job
  const signature = variation.signature

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>{contractor?.company_name || contractor?.full_name || 'Contractor'}</Text>
            <Text style={styles.docTitle}>Variation Notice</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={{ fontSize: 9, color: colors.gray400 }}>Date</Text>
            <Text style={{ fontSize: 10 }}>{fmtDate(variation.date)}</Text>
            <Text style={{ fontSize: 9, color: colors.gray400, marginTop: 6 }}>Ref</Text>
            <Text style={{ fontSize: 9, fontFamily: 'Helvetica-Bold' }}>{variation.id.slice(0, 8).toUpperCase()}</Text>
          </View>
        </View>

        <View style={[styles.row, { marginBottom: 24 }]}>
          <View style={{ flex: 1 }}>
            <Text style={styles.sectionTitle}>Job</Text>
            <Text style={styles.value}>{job?.job_name}</Text>
            <Text style={[styles.value, { color: colors.gray600, marginTop: 2 }]}>{job?.address}</Text>
          </View>
          <View style={{ flex: 1, alignItems: 'flex-end' }}>
            <Text style={styles.sectionTitle}>Client</Text>
            <Text style={styles.value}>{job?.client_name}</Text>
            <Text style={[styles.value, { color: colors.gray600, marginTop: 2 }]}>{job?.client_email}</Text>
          </View>
        </View>

        <View style={{ marginBottom: 24 }}>
          <Text style={styles.sectionTitle}>Variation Description</Text>
          <View style={{ backgroundColor: colors.gray100, borderRadius: 6, padding: 12, marginTop: 4 }}>
            <Text style={{ fontSize: 10, lineHeight: 1.5 }}>{variation.description}</Text>
          </View>
        </View>

        <View style={[styles.row, { marginBottom: 24 }]}>
          <View>
            <Text style={styles.label}>Additional Cost (exc. VAT)</Text>
            <Text style={{ fontSize: 24, fontFamily: 'Helvetica-Bold', color: colors.blue }}>{fmt(variation.cost)}</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={styles.label}>Status</Text>
            <View style={{
              backgroundColor: variation.status === 'signed' ? '#DCFCE7' : '#FEF3C7',
              borderRadius: 20, padding: '4 10',
            }}>
              <Text style={{
                fontSize: 9, fontFamily: 'Helvetica-Bold',
                color: variation.status === 'signed' ? colors.green : colors.amber,
                textTransform: 'uppercase',
              }}>
                {variation.status}
              </Text>
            </View>
          </View>
        </View>

        {signature && (
          <>
            <View style={styles.divider} />
            <View style={{ marginBottom: 16 }}>
              <Text style={styles.sectionTitle}>Client Sign-off</Text>
              <View style={[styles.row, { marginTop: 8 }]}>
                <View>
                  <Text style={styles.label}>Signed by</Text>
                  <Text style={styles.value}>{signature.client_name}</Text>
                  <Text style={styles.label}>Date signed</Text>
                  <Text style={styles.value}>{fmtDate(signature.signed_at)}</Text>
                </View>
                <View style={{ width: 160, height: 64, backgroundColor: colors.gray100, borderRadius: 6, padding: 4 }}>
                  <Image src={signature.signature_data} style={{ width: '100%', height: '100%', objectFit: 'contain' }} />
                </View>
              </View>
            </View>
          </>
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by VarTrack</Text>
          <Text style={styles.footerText}>Electronic signature valid under Electronic Communications Act 2000</Text>
        </View>
      </Page>
    </Document>
  )
}
